version: '3.8'
  services:
    front-tarkov:
      image: node:21-alpine
      restart: always
      container_name: front-tarkov
      ports:
        - '7234:8080'
      networks:
        - tarkov

  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tarkov
  networks:
    - tarkov

nginx:
   # Опциональный параметр с именем контейнера
   container_name: proxy_nginx
   image: nginx:latest
   ports:
     - "80:80"
     - "443:443"
   volumes:
     # Используем свой nginx конфиг, он заменит дефолтный в контейнере
     - ./nginx:/etc/nginx/conf.d
     # Монтируем папку с логами на хост машину для более удобного доступа
     - ./logs:/var/log/nginx/

  # admin:
  #   image: postgres:16-alpine
  #   restart: always
  #   container_name: postgres
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: tarkov
  # networks:
  #   - tarkov
